# 04 - Embeddings

## Goals
- Understand what an embedding is
- Understand why AI represents things as vectors
- Understand token IDs vs embedding vectors
- Understand `nn.Embedding`
- Understand embedding dimensions
- Understand that embedding values are learned parameters
- Understand vector similarity
- Understand cosine similarity conceptually
- Understand why similar meanings can end up near each other in embedding space

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# ------------
# CREATE A SMALL VOCABULARY
# --------------------------

words = [
    "dog",
    "cat",
    "truck",
    "car",
    "apple",
]

word_to_id = {
    "dog": 0,
    "cat": 1,
    "truck": 2,
    "car": 3,
    "apple": 4
}

# -----------
# CREATE EMBEDDING LAYER
# ----------------------

embedding = nn.Embedding(
    num_embeddings=5,
    embedding_dim=3
)

# --------------------------
# LOOK UP ONE WORD
# ------------------------

dog_id = torch.tensor(word_to_id["dog"])

dog_embedding = embedding(dog_id)

print("Dog ID: ")
print(dog_id)

print("\nDog embedding: ")
print(dog_embedding)

#----------------
# LOOK UP MULTIPLE WORDS
# -----------------------

word_ids = torch.tensor([
    word_to_id["dog"],
    word_to_id["cat"],
    word_to_id["truck"],

])

vectors = embedding(word_ids)

print("\nMultiple embeddings:")
print(vectors)

print("\nShape:")
print(vectors.shape)

# -------------------
# INSPECT ALL EMBEDDINGS
# ---------------------

print("\nEmbedding table:")
print(embedding.weight)

# ---------------------
# COMPARE TWO VECTORS
# -------------------

dog_vector = embedding(
    torch.tensor(word_to_id["dog"])
)

cat_vector = embedding(
    torch.tensor(word_to_id["cat"])
)

similarity = F.cosine_similarity(
    dog_vector.unsqueeze(0),
    cat_vector.unsqueeze(0)
)

print("\nDog / cat cosine similarity:")
print(similarity.item())


Dog ID: 
tensor(0)

Dog embedding: 
tensor([ 0.1368,  0.0612, -0.6351], grad_fn=<EmbeddingBackward0>)

Multiple embeddings:
tensor([[ 0.1368,  0.0612, -0.6351],
        [-0.8599, -0.1530, -1.0769],
        [ 0.5867,  1.0374,  0.7262]], grad_fn=<EmbeddingBackward0>)

Shape:
torch.Size([3, 3])

Embedding table:
Parameter containing:
tensor([[ 0.1368,  0.0612, -0.6351],
        [-0.8599, -0.1530, -1.0769],
        [ 0.5867,  1.0374,  0.7262],
        [-0.1306, -0.4144,  2.4067],
        [ 0.0794,  1.0925,  0.3457]], requires_grad=True)

Dog / cat cosine similarity:
0.6154863238334656
